### ISSUE TITLE
Extra empty strings displayed in vcardArray's vcardPostalInfo 

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-json-renderer#4]
When an user searches for an entity that contains a vcardArray object, if the vcardArray includes a vcardPostalInfo, the json displays two extra empty strings just after the attribute "text" for "adr" element and before "street1" element (just as shown below):

> 	[
> 								"adr",
> 								{
> 									"type": "WORK"
> 								},
> 								"text",
> 								[
> 									"",
> 									"",
> 									[
> 										"street 10 org",
> 										"calle segunda 2",
> 										"avenida tercera 33"
> 									],
> 									"org city",
> 									"NUEVO LEON",
> 									"12345",
> 									"org"
> 								]
> 							],
> 							[
> 								"adr",
> 								{
> 									"type": "home"
> 								},
> 								"text",
> 								[
> 									"",
> 									"",
> 									[
> 										"EUGENIO GARZA SADA",
> 										"LUIS ELIZONDO",
> 										"TEC"
> 									],
> 									"MONTERREY",
> 									"NUEVO LEON",
> 									"66666",
> 									"MEXICO"
> 								]

It seems the cause is these two lines in mx.nic.rdap.renderer.json.writer.VCardJsonWriter 

...
		// postal info
		JsonArrayBuilder postalInfoArray = Json.createArrayBuilder();

		postalInfoArray.add("");
		postalInfoArray.add("");

		JsonArrayBuilder streetBuilder = Json.createArrayBuilder();
...

Is there any reason to add these two empty strings?

**Comment by dhfelix** [comment]
Hello, sorry for the delay to attend this issue.

About the issue, there is a reason for the two empty values in the array, according to [RFC6350#section-6.3.1](https://tools.ietf.org/html/rfc6350#section-6.3.1), seven values in the "address" structure must be added, as the first two values are not requested from our data-access API (maybe in the future we could request them) we have to add to the structure two empty values to not break the standard.

Here is a quote from the RFC:

> Special notes:  The structured type value consists of a sequence of
>       address components.  The component values MUST be specified in
>       their corresponding position.  The structured type value
>       corresponds, in sequence, to
>          the post office box;
>          the extended address (e.g., apartment or suite number);
>          the street address;
>          the locality (e.g., city);
>          the region (e.g., state or province);
>          the postal code;
>          the country name (full name in the language specified in
>          Section 5.1).
> 
>       When a component value is missing, the associated component
>       separator MUST still be specified.

This issue will remain open, to document it in the code in the next release.

**Comment by TheRedTrainer** [comment]
Verified. This issue is invalid.
